/**
 * Tiered gambling keyword inventory for detectGamblingLanguage().
 * Definitive → terminal promote; strong → needs density/buddy; weak → never alone.
 */

/** @type {string[]} */
export const DEFINITIVE_GAMBLING_KEYWORDS = [
  "online betting site",
  "real money casino",
  "real-money casino",
  "mobile casino app",
  "gambling website",
  "betting website",
  "online gambling",
  "online casino",
  "live casino",
  "live dealers",
  "live dealer",
  "gambling site",
  "betting site",
  "sports book",
  "sportsbook",
  "sportbook",
  "casino app",
  "bookmakers",
  "bookmaker",
  "casinos",
  "casino",
];

/** @type {string[]} */
export const STRONG_GAMBLING_KEYWORDS = [
  // Casino / slots / mechanics (longer first)
  "progressive jackpot",
  "instant withdrawals",
  "instant withdrawal",
  "instant payouts",
  "instant payout",
  "fast withdrawals",
  "fast withdrawal",
  "fast payouts",
  "fast payout",
  "no deposit bonus",
  "slot machines",
  "slot machine",
  "return to player",
  "medium volatility",
  "high volatility",
  "low volatility",
  "slot volatility",
  "game volatility",
  "online slots",
  "video slots",
  "free spins",
  "free spin",
  "table games",
  "house edge",
  "megaways",
  "jackpot",
  "RTP",

  // Card / table
  "texas holdem",
  "texas hold'em",
  "omaha poker",
  "caribbean stud",
  "video poker",
  "blackjack",
  "baccarat",
  "roulette",
  "pai gow",
  "poker",
  "craps",

  // Sportsbook markets
  "live sports betting",
  "sports betting",
  "in-play betting",
  "in play betting",
  "asian handicap",
  "handicap bet",
  "point spread",
  "betting markets",
  "betting odds",
  "cash out bet",
  "cashout bet",
  "money line",
  "moneyline",
  "match odds",
  "over under",
  "over/under",
  "prop bets",
  "prop bet",
  "odds boost",
  "bet slip",
  "accumulator",
  "parlay",

  // Sports + wager cue
  "champions league betting",
  "champions league odds",
  "premier league betting",
  "premier league odds",
  "super bowl betting",
  "world cup betting",
  "euroleague betting",
  "basketball betting",
  "basketball odds",
  "football betting",
  "football odds",
  "baseball betting",
  "formula 1 betting",
  "table tennis betting",
  "volleyball betting",
  "horse racing betting",
  "greyhound betting",
  "Wimbledon betting",
  "soccer betting",
  "soccer odds",
  "tennis betting",
  "tennis odds",
  "hockey betting",
  "cricket betting",
  "cricket odds",
  "boxing betting",
  "racing odds",
  "FIFA betting",
  "golf betting",
  "darts betting",
  "snooker betting",
  "rugby betting",
  "F1 betting",
  "ATP betting",
  "IPL betting",
  "UFC betting",
  "MMA betting",
  "NFL betting",
  "NFL odds",
  "NBA betting",
  "NBA odds",
  "MLB betting",
  "MLB odds",
  "NHL betting",
  "NHL odds",

  // Esports + wager cue
  "live esports betting",
  "bet on esports",
  "e-sports betting",
  "esports betting",
  "esports odds",
  "Counter-Strike betting",
  "League of Legends betting",
  "Call of Duty betting",
  "Mobile Legends betting",
  "Rocket League betting",
  "FIFA esports betting",
  "StarCraft betting",
  "Overwatch betting",
  "Valorant betting",
  "Wild Rift betting",
  "eFootball betting",
  "Dota 2 betting",
  "LoL betting",
  "PUBG betting",
  "CS2 betting",
];

/** @type {string[]} */
export const WEAK_GAMBLING_KEYWORDS = [
  "betting",
  "bets",
  "bet",
  "odds",
  "slots",
  "slot",
  "spins",
  "spin",
  "volatility",
  "payouts",
  "payout",
  "withdrawals",
  "withdrawal",
  "bingo",
  "keno",
  // Bare sports / leagues / titles (no wager cue)
  "Premier League",
  "Champions League",
  "football",
  "soccer",
  "basketball",
  "baseball",
  "tennis",
  "hockey",
  "cricket",
  "boxing",
  "rugby",
  "NBA",
  "NFL",
  "MLB",
  "NHL",
  "UFC",
  "MMA",
  "IPL",
  "Dota 2",
  "Valorant",
  "Overwatch",
  "Counter-Strike",
  "League of Legends",
  "Mobile Legends",
  "PUBG",
  "CS2",
];

/** Capacity / availability phrases that must not count as gambling (even weak). */
export const GAMBLING_CONTEXT_VETOES = [
  "limited slots",
  "time slots",
  "time slot",
  "parking slot",
  "SIM slot",
  "job slot",
  "expansion slot",
  "interview slot",
];
